export const PROJECTS = [
  {
    id: 7,
    title: "Zariyaa Matrimony",
    description: "AI-based career guidance platform using LangChain and OpenAI to recommend personalized learning paths.",
    techStack: ["Django","GCP", "Python", "PostgresQL",],
    image: "/zariyaa.png",
    demoUrl: "https://educationist.ai/",
    codeUrl: "https://github.com/Umair-Rinde",
    stars:0,
    forks:0,
    status: "Stable",
  },  
  {
      id: 1,
      title: "Educationist.ai",
      description: "AI-based career guidance platform using LangChain and OpenAI to recommend personalized learning paths.",
      techStack: ["LangChain", "ChatGPT", "Python", "MongoDB", "React"],
      image: "/educationst.png",
      demoUrl: "https://educationist.ai/",
      codeUrl: "https://github.com/Umair-Rinde",
    stars:0,
    forks:0,
    status: "Stable",
    },
    {
      id: 2,
      title: "Career View App",
      description: "Mock interview and job-seeking mobile platform helping users prepare for real job roles using AI.",
      techStack: ["React Native", "Firebase", "Python", "MongoDB"],
      image: "/career.png",
      demoUrl: "https://careerview.fladdra.com/",
      codeUrl: "https://github.com/Umair-Rinde",
      stars:0,
      forks:0,
      status: "Mobile",
    },
    {
      id: 8,
      title: "ITSM Project (Fladdra Consultancy)",
      description: "Incident management system built using Django and React. Supports email-to-ticket automation using Google Console.",
      techStack: ["Django", "React", "Google Cloud", "Azure", "SMTP"],
      image: "/itsm.png",
      demoUrl: "https://dev.bizitsm.com/user-login",
      codeUrl: "https://github.com/Umair-Rinde",
      stars:0,
      forks:0,
      status: "Enterprise",
    },
    {
      id: 3,
      title: "CRM Project (Fladdra Consultancy)",
      description: "Customer Resource Management system built using Django and React. Designed to help businesses track customer interactions and manage sales pipelines.",
      techStack: ["Django", "React", "Azure"],
      image: "/crm.png",
      demoUrl: "https://fladdra.easymaktab.com",
      codeUrl: "https://github.com/Umair-Rinde",
      stars:0,
      forks:0,
      status: "Enterprise",
    },
    {
      id: 4,
      title: "LMS - Learning Management System",
      description: "A full-featured LMS with blogs, course enrollment, authentication, and video streaming. Built with NestJS backend.",
      techStack: ["NestJS", "PostgreSQL", "NEXT.JS", "JWT"],
      image: "/lms.png",
      codeUrl: "https://github.com/Umair-Rinde",
      stars:0,
      forks:0,
      status: "Production",
    },
    {
      id: 5,
      title: "FEMS - Farmer Empowerment System",
      description: "A government-funded platform enabling farmers to access resources, expert advice, and track agricultural data with ease.",
      techStack: ["React", "NestJS", "MongoDB", "JWT", "Tailwind"],
      image: "/fems.png",
      demoUrl: "https://fems-4qqz.vercel.app/auth/login",
      codeUrl: "https://github.com/Umair-Rinde/fems",
      stars:0,
      forks:2,
      status: "Production",
    },
    {
      id: 6,
      title: "Human Intrusion Detection System",
      description: "Camera-based real-time human detection using Flask and Arduino. Sends alerts via SMS using Twilio.",
      techStack: ["Flask", "Python", "Arduino", "SQLite", "Twilio"],
      image: "/hids.png",
      codeUrl: "https://github.com/Umair-Rinde",
      stars:0,
      forks:0,
      status: "Scale",
    },
  ];
  